// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_have_a_soda_or_something = "CgkI-MWr7rcKEAIQBg"; // <GPGSID>
        public const string achievement_jeweler = "CgkI-MWr7rcKEAIQBw"; // <GPGSID>
        public const string achievement_die_die_die = "CgkI-MWr7rcKEAIQAw"; // <GPGSID>
        public const string achievement_second_chance = "CgkI-MWr7rcKEAIQDA"; // <GPGSID>
        public const string leaderboard_highscores = "CgkI-MWr7rcKEAIQCg"; // <GPGSID>
        public const string achievement_3_lives_aint_enough = "CgkI-MWr7rcKEAIQDQ"; // <GPGSID>
        public const string achievement_millionaire = "CgkI-MWr7rcKEAIQCA"; // <GPGSID>
        public const string achievement_mastering_death = "CgkI-MWr7rcKEAIQBA"; // <GPGSID>
        public const string achievement_master_of_revival = "CgkI-MWr7rcKEAIQDg"; // <GPGSID>
        public const string achievement_i_can_revive_forever = "CgkI-MWr7rcKEAIQDw"; // <GPGSID>
        public const string achievement_rise_and_shine_again = "CgkI-MWr7rcKEAIQAg"; // <GPGSID>
        public const string achievement_bitcoin = "CgkI-MWr7rcKEAIQCQ"; // <GPGSID>
        public const string achievement_you_cant_be_serious = "CgkI-MWr7rcKEAIQBQ"; // <GPGSID>
        public const string achievement_inconceivable = "CgkI-MWr7rcKEAIQEA"; // <GPGSID>

}

